---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.install_maxscale"
      tags:
        - "labocbz.install_maxscale"
      vars:
        install_maxscale__admin_login: "{{ inv_install_maxscale__admin_login }}"
        install_maxscale__admin_password: "{{ inv_install_maxscale__admin_password }}"
        install_maxscale__database_user_login: "{{ inv_install_maxscale__database_user_login }}"
        install_maxscale__database_user_password: "{{ inv_install_maxscale__database_user_password }}"
        install_maxscale__mariadb_servers: "{{ inv_install_maxscale__mariadb_servers }}"
        install_maxscale__mariadb_server_ssl: "{{ inv_install_maxscale__mariadb_server_ssl }}"
        install_maxscale__mariadb_server_type: "{{ inv_install_maxscale__mariadb_server_type }}"
        install_maxscale__mariadb_server_ssl_ca: "{{ inv_install_maxscale__mariadb_server_ssl_ca }}"
        install_maxscale__mariadb_server_ssl_client_auth: "{{ inv_install_maxscale__mariadb_server_ssl_client_auth }}"
        install_maxscale__mariadb_server_ssl_cert: "{{ inv_install_maxscale__mariadb_server_ssl_cert }}"
        install_maxscale__mariadb_server_ssl_key: "{{ inv_install_maxscale__mariadb_server_ssl_key }}"
        install_maxscale__mariadb_server_ssl_version: "{{ inv_install_maxscale__mariadb_server_ssl_version }}"
        install_maxscale__mariadb_server_ssl_verify_peer_certificate: "{{ inv_install_maxscale__mariadb_server_ssl_verify_peer_certificate }}"
        install_maxscale__mariadb_server_ssl_verify_peer_host: "{{ inv_install_maxscale__mariadb_server_ssl_verify_peer_host }}"
        install_maxscale__listener_server_port: "{{ inv_install_maxscale__listener_server_port }}"
        install_maxscale__listener_server_address: "{{ inv_install_maxscale__listener_server_address }}"
        install_maxscale__listener_server_ssl: "{{ inv_install_maxscale__listener_server_ssl }}"
        install_maxscale__listener_server_ssl_client_auth: "{{ inv_install_maxscale__listener_server_ssl_client_auth }}"
        install_maxscale__listener_server_ssl_ca: "{{ inv_install_maxscale__listener_server_ssl_ca }}"
        install_maxscale__listener_server_ssl_cert: "{{ inv_install_maxscale__listener_server_ssl_cert }}"
        install_maxscale__listener_server_ssl_key: "{{ inv_install_maxscale__listener_server_ssl_key }}"
        install_maxscale__threads: "{{ inv_install_maxscale__threads }}"
        install_maxscale__admin_enabled: "{{ inv_install_maxscale__admin_enabled }}"
        install_maxscale__admin_gui: "{{ inv_install_maxscale__admin_gui }}"
        install_maxscale__admin_host: "{{ inv_install_maxscale__admin_host }}"
        install_maxscale__admin_port: "{{ inv_install_maxscale__admin_port }}"
        install_maxscale__admin_secure_gui: "{{ inv_install_maxscale__admin_secure_gui }}"
        install_maxscale__admin_ssl_ca: "{{ inv_install_maxscale__admin_ssl_ca }}"
        install_maxscale__admin_ssl_cert: "{{ inv_install_maxscale__admin_ssl_cert }}"
        install_maxscale__admin_ssl_key: "{{ inv_install_maxscale__admin_ssl_key }}"
      ansible.builtin.include_role:
        name: "labocbz.install_maxscale"
